In [1]:
import pandas as pd

In [12]:
data = pd.read_csv('exchangerates.csv')
data

,date,myr_usd,myr_rmb,myr_sgd,myr_eur,myr_jpy,myr_twd,myr_thb,myr_idr,myr_hkd,...,myr_aed,myr_sar,myr_try,myr_gbp,myr_brl,myr_mxn,myr_bdt,myr_chf,myr_cad,myr_rub
0,2003-12-01,0.263380,2.177413,0.453461,0.220125,28.753161,8.359132,10.506216,2238.306086,2.045143,...,0.966999,0.987621,0.353535,0.153253,0.769859,2.991467,14.910451,0.341893,0.343500,7.822377
1,2003-12-02,0.263359,2.177241,0.452977,0.217850,28.635010,8.359132,10.494587,2234.889529,2.043507,...,0.966922,0.987543,0.353535,0.152203,0.771905,2.973322,14.934028,0.338996,0.341471,7.819125
2,2003-12-03,0.263838,2.181178,0.452773,0.217635,28.573691,8.359132,10.502612,2234.156621,2.047491,...,0.968682,0.989341,0.353535,0.152675,0.773310,2.966862,14.980212,0.339085,0.343016,7.833360
3,2003-12-04,0.263248,2.176271,0.451075,0.217903,28.501853,8.359132,10.495695,2235.633105,2.044463,...,0.966515,0.987127,0.353535,0.152989,0.774739,2.945218,14.935109,0.339195,0.345223,7.813199
4,2003-12-05,0.263880,2.181470,0.452290,0.216527,28.398777,8.359132,10.505859,2234.826884,2.047630,...,0.968915,0.989498,0.353535,0.152259,0.774224,2.954665,14.977571,0.335761,0.343809,7.816129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7612,2024-10-03,0.239751,1.687293,0.309767,0.216998,35.143130,7.626948,7.885638,3673.939014,1.861105,...,0.880364,0.898661,8.206808,0.180724,1.304315,4.653128,28.249908,0.203766,0.323781,22.931386
7613,2024-10-04,0.237107,1.670445,0.307315,0.214857,34.816832,7.591701,7.850622,3664.967179,1.841228,...,0.870658,0.889203,8.115423,0.180581,1.298471,4.584588,27.970692,0.201970,0.321238,22.404861
7614,2024-10-05,0.237107,1.670445,0.307315,0.214857,34.816832,7.591701,7.850622,3664.967179,1.841228,...,0.870658,0.889203,8.115423,0.180581,1.298471,4.584588,27.970692,0.201970,0.321238,22.404861
7615,2024-10-06,0.237107,1.670445,0.307315,0.214857,34.816832,7.591701,7.850622,3664.967179,1.841228,...,0.870658,0.889203,8.115423,0.180581,1.298471,4.584588,27.970692,0.201970,0.321238,22.404861
7616,2024-10-07,0.233754,1.640393,0.304689,0.212786,34.624826,7.517298,7.816737,3663.861739,1.815409,...,0.858555,0.877279,8.009430,0.178595,1.281908,4.516183,28.022441,0.199670,0.318069,22.458158

In [13]:
# I only need the records from 2024 onwards 
# date format is (YYYY-MM-DD)
data['date'] = pd.to_datetime(data['date'])
data = data[data['date'].dt.year >= 2024]
data

,date,myr_usd,myr_rmb,myr_sgd,myr_eur,myr_jpy,myr_twd,myr_thb,myr_idr,myr_hkd,...,myr_aed,myr_sar,myr_try,myr_gbp,myr_brl,myr_mxn,myr_bdt,myr_chf,myr_cad,myr_rub
7336,2024-01-01,0.217746,1.539162,0.287273,0.197256,30.729668,6.677975,7.474360,3349.591600,1.700525,...,0.799521,0.816440,6.407882,0.171066,1.056592,3.693524,23.608981,0.183318,0.288340,19.426237
7337,2024-01-02,0.217344,1.540882,0.288272,0.198637,30.896545,6.711367,7.435340,3368.398250,1.698529,...,0.798044,0.814022,6.464869,0.172180,1.069876,3.699065,23.504744,0.184769,0.289546,19.646816
7338,2024-01-03,0.217344,1.542904,0.288718,0.198892,31.079982,6.746773,7.485329,3380.786862,1.696914,...,0.798044,0.814131,6.472306,0.171484,1.069159,3.697490,23.473008,0.184503,0.290104,19.988046
7339,2024-01-04,0.215843,1.534643,0.286939,0.197164,31.246493,6.702785,7.444204,3347.938801,1.685539,...,0.792532,0.808537,6.440946,0.170168,1.056680,3.671185,23.330475,0.183466,0.288258,19.709692
7340,2024-01-05,0.214961,1.524613,0.285817,0.196451,31.108341,6.653482,7.445615,3327.063602,1.679114,...,0.789295,0.806062,6.402468,0.169024,1.044855,3.628749,23.171434,0.182874,0.287184,19.538907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7612,2024-10-03,0.239751,1.687293,0.309767,0.216998,35.143130,7.626948,7.885638,3673.939014,1.861105,...,0.880364,0.898661,8.206808,0.180724,1.304315,4.653128,28.249908,0.203766,0.323781,22.931386
7613,2024-10-04,0.237107,1.670445,0.307315,0.214857,34.816832,7.591701,7.850622,3664.967179,1.841228,...,0.870658,0.889203,8.115423,0.180581,1.298471,4.584588,27.970692,0.201970,0.321238,22.404861
7614,2024-10-05,0.237107,1.670445,0.307315,0.214857,34.816832,7.591701,7.850622,3664.967179,1.841228,...,0.870658,0.889203,8.115423,0.180581,1.298471,4.584588,27.970692,0.201970,0.321238,22.404861
7615,2024-10-06,0.237107,1.670445,0.307315,0.214857,34.816832,7.591701,7.850622,3664.967179,1.841228,...,0.870658,0.889203,8.115423,0.180581,1.298471,4.584588,27.970692,0.201970,0.321238,22.404861
7616,2024-10-07,0.233754,1.640393,0.304689,0.212786,34.624826,7.517298,7.816737,3663.861739,1.815409,...,0.858555,0.877279,8.009430,0.178595,1.281908,4.516183,28.022441,0.199670,0.318069,22.458158

In [14]:
# save the data to a new csv file
data.to_csv('exchangerates_2024.csv', index=False)

In [5]:
import pandas as pd

# Load the dataset
df = pd.read_csv('exchangerates.csv')

# Convert the 'date' column to datetime format
df['date'] = pd.to_datetime(df['date'])

# Filter for rows starting from 2024-01-01
filtered_df = df[df['date'] >= '2024-01-01']

# List of exchange rate columns
exchange_rate_columns = [
    'myr_usd', 'myr_rmb', 'myr_sgd', 'myr_eur', 'myr_jpy', 'myr_twd', 'myr_thb', 'myr_idr', 
    'myr_hkd', 'myr_krw', 'myr_vnd', 'myr_inr', 'myr_aud', 'myr_php', 'myr_aed', 'myr_sar', 
    'myr_try', 'myr_gbp', 'myr_brl', 'myr_mxn', 'myr_bdt', 'myr_chf', 'myr_cad', 'myr_rub'
]

# Melt the dataset to have a country column and the exchange rate
df_melted = filtered_df.melt(id_vars=['date'], value_vars=exchange_rate_columns, 
                             var_name='currency', value_name='exchange_rate')

# Calculate average exchange rate for each currency in 2024
avg_exchange_rates = df_melted.groupby('currency')['exchange_rate'].mean().reset_index()

# Map the 'currency' column to country names or ISO country codes that match TopoJSON
currency_to_country = {
    'myr_usd': 'United States of America',  
    'myr_rmb': 'China', 
    'myr_sgd': 'Singapore', 

    # Euro Area countries
    'myr_eur': ['France', 'Germany', 'Italy', 'Spain', 'Netherlands', 'Belgium', 'Austria', 
                'Portugal', 'Finland', 'Greece', 'Ireland', 'Slovakia', 'Slovenia', 'Cyprus', 
                'Estonia', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Monaco', 'San Marino', 
                'Vatican City', 'Andorra', 'Kosovo', 'Montenegro'],
    
    'myr_jpy': 'Japan', 
    'myr_twd': 'Taiwan', 
    'myr_thb': 'Thailand', 
    'myr_idr': 'Indonesia', 
    'myr_hkd': 'Hong Kong SAR', 
    'myr_krw': 'Korea, Republic of',  
    'myr_vnd': 'Vietnam', 
    'myr_inr': 'India', 
    'myr_aud': 'Australia', 
    'myr_php': 'Philippines', 
    'myr_sar': 'Saudi Arabia', 
    'myr_try': 'Turkey', 
    'myr_gbp': 'United Kingdom', 
    'myr_brl': 'Brazil', 
    'myr_mxn': 'Mexico', 
    'myr_bdt': 'Bangladesh', 
    'myr_chf': 'Switzerland', 
    'myr_cad': 'Canada', 
    'myr_rub': 'Russia'
}

# Create a new DataFrame for Euro countries
euro_df = pd.DataFrame()

# Add the same exchange rate for each Euro country
avg_eur_rate = avg_exchange_rates[avg_exchange_rates['currency'] == 'myr_eur']['exchange_rate'].values[0]
for country in currency_to_country['myr_eur']:
    euro_df = pd.concat([euro_df, pd.DataFrame({'currency': ['myr_eur'], 'exchange_rate': [avg_eur_rate], 'country': [country]})], ignore_index=True)

# Apply the mapping for single country currencies
avg_exchange_rates['country'] = avg_exchange_rates['currency'].map(lambda x: currency_to_country.get(x) if isinstance(currency_to_country.get(x), str) else None)

# Combine the Euro countries DataFrame with the main DataFrame
avg_exchange_rates = pd.concat([avg_exchange_rates, euro_df], ignore_index=True)

# Drop any rows where the 'country' column is NaN (for example, UAE)
avg_exchange_rates = avg_exchange_rates.dropna(subset=['country'])

# Save the dataset for Vega-Lite
avg_exchange_rates[['country', 'exchange_rate']].to_csv('avg_exchange_rates_2024.csv', index=False)

In [6]:
import csv
from io import StringIO

# Define a dictionary mapping countries to their currency codes
country_to_currency = {
    "Australia": "AUD",
    "Bangladesh": "BDT",
    "Brazil": "BRL",
    "Canada": "CAD",
    "Switzerland": "CHF",
    "United Kingdom": "GBP",
    "Hong Kong SAR": "HKD",
    "Indonesia": "IDR",
    "India": "INR",
    "Japan": "JPY",
    "South Korea": "KRW",
    "Mexico": "MXN",
    "Philippines": "PHP",
    "China": "CNY",
    "Russia": "RUB",
    "Saudi Arabia": "SAR",
    "Singapore": "SGD",
    "Thailand": "THB",
    "Turkey": "TRY",
    "Taiwan": "TWD",
    "United States of America": "USD",
    "Vietnam": "VND",
    "Pakistan": "PKR",
    "Sri Lanka": "LKR",
    "Ukraine": "UAH",
    "South Africa": "ZAR",
    "Namibia": "NAD",
    "Zimbabwe": "ZWL",
    "Zambia": "ZMW",
    "Botswana": "BWP",
    "Lesotho": "LSL",
    "Eswatini": "SZL",
    "Mozambique": "MZN",
    "Malawi": "MWK",
    "Tanzania": "TZS",
    "Uganda": "UGX",
    "Kenya": "KES",
    "Rwanda": "RWF",
    "Burundi": "BIF",
    "Somalia": "SOS",
    "Ethiopia": "ETB",
    "Djibouti": "DJF",
    "Sudan": "SDG",
    "South Sudan": "SSP",
    "Cameroon": "XAF",
    "Nigeria": "NGN",
    "Ghana": "GHS",
    "Central African Republic": "XAF",
    "Chad": "XAF",
    "Equatorial Guinea": "XAF",
    "Gabon": "XAF",
    "Congo": "XAF",
    "Democratic Republic of the Congo": "CDF",
    "Angola": "AOA",
    "Kazakhstan": "KZT",
    "Uzbekistan": "UZS",
    "Turkmenistan": "TMT",
    "Belarus": "BYN",
    "Kyrgyzstan": "KGS",
    "Tajikistan": "TJS",
    "Armenia": "AMD",
    "Azerbaijan": "AZN",
    "Georgia": "GEL",
    "Mongolia": "MNT",
    "Iran": "IRR",
    "Iraq": "IQD",
    "Afghanistan": "AFN",
    "Syria": "SYP",
    "Jordan": "JOD",
    "Cuba": "CUP",
    "Peru": "PEN",
    "Argentina": "ARS",
    "Bolivia": "BOB",
    "Chile": "CLP",
    "Paraguay": "PYG",
    "Uruguay": "UYU",
    "Honduras": "HNL",
    "Nicaragua": "NIO",
    "Costa Rica": "CRC",
    "Madagascar": "MGA",
    "Dem. Rep. Congo": "CDF",
    "Egypt": "EGP",
    "Libya": "LYD",
    "Algeria": "DZD",
    "Mali": "XOF",
    "Mauritania": "MRU",
    "Morocco": "MAD",
    "Senegal": "XOF",
    "Bulgaria": "BGN",
    "Sweden": "SEK",
    "Norway": "NOK",
    "Greenland": "DKK",
    "Denmark": "DKK",
    "Poland": "PLN",
    "Yemen": "YER",
    "Oman": "OMR",
    "Qatar": "QAR",
    "Myanmar": "MMK",
    "Cambodia": "KHR",
    "Papua New Guinea": "PGK",
    "New Zealand": "NZD",
    "Niger": "XOF"
}

# For countries in the Eurozone
eurozone_countries = [
    "France", "Germany", "Italy", "Spain", "Netherlands", "Belgium", "Austria",
    "Portugal", "Finland", "Greece", "Ireland", "Slovakia", "Slovenia", "Cyprus",
    "Estonia", "Latvia", "Lithuania", "Luxembourg", "Malta", "Monaco", "San Marino",
    "Vatican City", "Andorra", "Kosovo", "Montenegro", "North Macedonia"
]

for country in eurozone_countries:
    country_to_currency[country] = "EUR"

# Your CSV data as a string
csv_data = """country,exchange_rate
Australia,0.3267588709901061
Bangladesh,24.416735233817782
Brazil,1.1369741318746842
Canada,0.29463628383945906
Switzerland,0.19067785144053762
United Kingdom,0.16945981445008323
Hong Kong SAR,1.6924694353902316
Indonesia,3433.2303673244473
India,18.078835429980977
Japan,32.69842004904345
"South Korea",292.5657847999815
Mexico,3.8567314896534413
Philippines,12.332827033280495
China,1.5557026250808514
Russia,19.562486044125517
Saudi Arabia,0.8118690408070979
Singapore,0.28941958156901165
Thailand,7.709362729436398
Turkey,7.019491819779123
Taiwan,6.930471647087664
United States of America,0.21668540386754845
Vietnam,5409.006607895432
France,0.199169324391188
Germany,0.199169324391188
Italy,0.199169324391188
Spain,0.199169324391188
Netherlands,0.199169324391188
Belgium,0.199169324391188
Austria,0.199169324391188
Portugal,0.199169324391188
Finland,0.199169324391188
Greece,0.199169324391188
Ireland,0.199169324391188
Slovakia,0.199169324391188
Slovenia,0.199169324391188
Cyprus,0.199169324391188
Estonia,0.199169324391188
Latvia,0.199169324391188
Lithuania,0.199169324391188
Luxembourg,0.199169324391188
Malta,0.199169324391188
Monaco,0.199169324391188
San Marino,0.199169324391188
Vatican City,0.199169324391188
Andorra,0.199169324391188
Kosovo,0.199169324391188
Montenegro,0.199169324391188
North Macedonia,0.199169324391188
Pakistan,64.794162
Sri Lanka,68.500594
Ukraine,9.6246285
South Africa,4.1043474
Namibia,4.1043474
Zimbabwe,4.1043474
Zambia,4.1043474
Botswana,4.1043474
Lesotho,4.1043474
Eswatini,4.1043474
Mozambique,4.1043474
Malawi,4.1043474
Tanzania,4.1043474
Uganda,4.1043474
Kenya,4.1043474
Rwanda,4.1043474
Burundi,4.1043474
Somalia,4.1043474
Ethiopia,4.1043474
Djibouti,4.1043474
Sudan,4.1043474
South Sudan,4.1043474
Cameroon,0.0076305
Nigeria,0.0076305
Ghana,0.0076305
Central African Republic,0.0076305
Chad,0.0076305
Equatorial Guinea,0.0076305
Gabon,0.0076305
Congo,0.0076305
Democratic Republic of the Congo,0.0076305
Angola,0.0076305
Kazakhstan,112.50 
Uzbekistan,9750.00
Turkmenistan,1.22
Belarus,29.00
Kyrgyzstan,75.00
Tajikistan,2.53
Armenia,410.00
Azerbaijan,56.00
Georgia,29.00
Mongolia,30.00
Iran,30000.00
Iraq,1450.00
Afghanistan,80.00
Syria,515.00
Jordan,0.71
Cuba,6.00
Peru,0.85
Argentina,232.77
Bolivia,1.63
Chile,218.49
Paraguay,1600.00
Uruguay,8.50
Honduras,5.80
Nicaragua,8.50
Costa Rica,650.00
Madagascar,1000.00
Dem. Rep. Congo,500.00
Central African Rep.,140.00
Egypt,11.60
Libya,1.13
Algeria,32.00
Mali,140.00
Mauritania,8.5
Morocco,2.35
Senegal,140.00
S. Sudan,30.00
Bulgaria,0.42
Sweden,2.46
Norway,2.53
Greenland,1.62
Denmark,1.62
Poland,0.42
Yamen,60.00
Oman,0.09
Qatar,3.64
Myanmar,500.00
Cambodia,1000.00
Papua New Guinea,0.80
New Zealand,0.38
Niger,140.00"""

# Read the CSV data
csv_reader = csv.reader(StringIO(csv_data))
header = next(csv_reader)
rows = list(csv_reader)

# Add the currency code column
header.append("currency_code")
for row in rows:
    country = row[0]
    currency_code = country_to_currency.get(country, "Unknown")
    row.append(currency_code)

# Create a new CSV string with the added column
output = StringIO()
csv_writer = csv.writer(output)
csv_writer.writerow(header)
csv_writer.writerows(rows)

# Print the updated CSV
print(output.getvalue())

country,exchange_rate,currency_code
Australia,0.3267588709901061,AUD
Bangladesh,24.416735233817782,BDT
Brazil,1.1369741318746842,BRL
Canada,0.29463628383945906,CAD
Switzerland,0.19067785144053762,CHF
United Kingdom,0.16945981445008323,GBP
Hong Kong SAR,1.6924694353902316,HKD
Indonesia,3433.2303673244473,IDR
India,18.078835429980977,INR
Japan,32.69842004904345,JPY
South Korea,292.5657847999815,KRW
Mexico,3.8567314896534413,MXN
Philippines,12.332827033280495,PHP
China,1.5557026250808514,CNY
Russia,19.562486044125517,RUB
Saudi Arabia,0.8118690408070979,SAR
Singapore,0.28941958156901165,SGD
Thailand,7.709362729436398,THB
Turkey,7.019491819779123,TRY
Taiwan,6.930471647087664,TWD
United States of America,0.21668540386754845,USD
Vietnam,5409.006607895432,VND
France,0.199169324391188,EUR
Germany,0.199169324391188,EUR
Italy,0.199169324391188,EUR
Spain,0.199169324391188,EUR
Netherlands,0.199169324391188,EUR
Belgium,0.199169324391188,EUR
Austria,0.199169324391188,EUR
Portugal,0.199169324391188,EUR
Finland,0.199169324391188,EUR
Greece,0.199169324391188,EUR
Ireland,0.199169324391188,EUR
Slovakia,0.199169324391188,EUR
Slovenia,0.199169324391188,EUR
Cyprus,0.199169324391188,EUR
Estonia,0.199169324391188,EUR
Latvia,0.199169324391188,EUR
Lithuania,0.199169324391188,EUR
Luxembourg,0.199169324391188,EUR
Malta,0.199169324391188,EUR
Monaco,0.199169324391188,EUR
San Marino,0.199169324391188,EUR
Vatican City,0.199169324391188,EUR
Andorra,0.199169324391188,EUR
Kosovo,0.199169324391188,EUR
Montenegro,0.199169324391188,EUR
North Macedonia,0.199169324391188,EUR
Pakistan,64.794162,PKR
Sri Lanka,68.500594,LKR
Ukraine,9.6246285,UAH
South Africa,4.1043474,ZAR
Namibia,4.1043474,NAD
Zimbabwe,4.1043474,ZWL
Zambia,4.1043474,ZMW
Botswana,4.1043474,BWP
Lesotho,4.1043474,LSL
Eswatini,4.1043474,SZL
Mozambique,4.1043474,MZN
Malawi,4.1043474,MWK
Tanzania,4.1043474,TZS
Uganda,4.1043474,UGX
Kenya,4.1043474,KES
Rwanda,4.1043474,RWF
Burundi,4.1043474,BIF
Somalia,4.1043474,SOS
Ethiopia,4.1043474,ETB
Djibouti,4.1043474,DJF
Sudan,4.1043474,SDG
South Sudan,4.1043474,SSP
Cameroon,0.0076305,XAF
Nigeria,0.0076305,NGN
Ghana,0.0076305,GHS
Central African Republic,0.0076305,XAF
Chad,0.0076305,XAF
Equatorial Guinea,0.0076305,XAF
Gabon,0.0076305,XAF
Congo,0.0076305,XAF
Democratic Republic of the Congo,0.0076305,CDF
Angola,0.0076305,AOA
Kazakhstan,112.50 ,KZT
Uzbekistan,9750.00,UZS
Turkmenistan,1.22,TMT
Belarus,29.00,BYN
Kyrgyzstan,75.00,KGS
Tajikistan,2.53,TJS
Armenia,410.00,AMD
Azerbaijan,56.00,AZN
Georgia,29.00,GEL
Mongolia,30.00,MNT
Iran,30000.00,IRR
Iraq,1450.00,IQD
Afghanistan,80.00,AFN
Syria,515.00,SYP
Jordan,0.71,JOD
Cuba,6.00,CUP
Peru,0.85,PEN
Argentina,232.77,ARS
Bolivia,1.63,BOB
Chile,218.49,CLP
Paraguay,1600.00,PYG
Uruguay,8.50,UYU
Honduras,5.80,HNL
Nicaragua,8.50,NIO
Costa Rica,650.00,CRC
Madagascar,1000.00,MGA
Dem. Rep. Congo,500.00,CDF
Central African Rep.,140.00,Unknown
Egypt,11.60,EGP
Libya,1.13,LYD
Algeria,32.00,DZD
Mali,140.00,XOF
Mauritania,8.5,MRU
Morocco,2.35,MAD
Senegal,140.00,XOF
S. Sudan,30.00,Unknown
Bulgaria,0.42,BGN
Sweden,2.46,SEK
Norway,2.53,NOK
Greenland,1.62,DKK
Denmark,1.62,DKK
Poland,0.42,PLN
Yamen,60.00,Unknown
Oman,0.09,OMR
Qatar,3.64,QAR
Myanmar,500.00,MMK
Cambodia,1000.00,KHR
Papua New Guinea,0.80,PGK
New Zealand,0.38,NZD
Niger,140.00,XOF

In [1]:
# clean the money aggregates to have only 2024 data
import pandas as pd

# Load the dataset
df = pd.read_csv('interest_rates.csv')

# Convert the 'date' column to datetime format
df['date'] = pd.to_datetime(df['date'])

# Filter for rows every year 1st month
filtered_df = df[df['date'].dt.month == 1]

# save the data to a new csv file
filtered_df.to_csv('interest_rates_2024.csv', index=False)

In [1]:
# only need the 2013 onwards data
import pandas as pd

# Load the dataset
df = pd.read_csv('interest_rates.csv')

# Convert the 'date' column to datetime format
df['date'] = pd.to_datetime(df['date'])

# Filter for rows starting from 2013
filtered_df = df[df['date'].dt.year >= 2013]

# Save the filtered dataset to a new CSV file
filtered_df.to_csv('interest_rates.csv', index=False)